# Generated by Django 5.0.6 on 2024-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='albums/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='songs/'),
        ),
    ]
