# Generated by Django 5.0.6 on 2024-07-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_artist_bio_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='artists/', verbose_name='Фото артиста'),
        ),
    ]
